### ISSUE TITLE
Proper way to log an exception

### ISSUE THREAD

**Issue by amccool** [serilog-trace-listener/serilog-diagnostics-tracelistener#28]
using a TraceSource, whats the proper way we should be logging Exceptions?

`
            catch (Exception ex)
            {
                _traceSource.TraceData( TraceEventType.Error, 34000, ex);
                throw;
            }
`

**Comment by TysonMN** [comment]
Why are you asking how to log an exception to `System.Diagnostics.Trace`?  Why not log the exception directly to Serilog?

**Comment by amccool** [comment]
this is over a year old.   Moved on.  closing...
